import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar/Navbar";
// import { Provider } from "react-redux";
// import { store } from "@/Redux/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
   subsets:["latin"],
  weight: ['300']

})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} text-[16px] antialiased`}
      >
        {/* <Provider store={store()}> */}
        <Navbar></Navbar>
        {children}
        {/* </Provider> */}
      </body>
    </html>
  );
}
